//
//  Environment+mock.swift
//  GithubStargazers
//
//  Created by Jean Raphael Bordet on 25/05/21.
//

import Foundation


extension AppEnvironment {
	static var mock = Self(
		stargazersEnv: StargazerViewEnvironment.mock
	)
}

extension StargazerViewEnvironment {
	static var mock = Self(
		stargazersEnv: StargazersEnvironment.mock
	)
}

extension StargazersEnvironment {
	static var mock = Self(
		fetch: { _, _, page in
			
			print("[StargazersEnvironment] mock \(page)")
			
			if page == 1 {
				return .just(page_1_mock())
			} else if page == 2 {
				return .just(page_2_mock())
			} else if page == 3 {
				return .just(page_3_mock())
			} else {
				return .just([])
			}
			
		}
	)
}

func page_1_mock() -> [StargazersModel] {
	do {
		let models = try JSONDecoder().decode([StargazerRequestModel].self, from: page_1.data(using: .utf8)!)
		return models.map { (m: StargazerRequestModel) -> StargazersModel in
				let model = StargazersModel(
					name: m.login,
					imageUrl: URL(string: m.avatar_url)
				)
				
				return model
			}
	} catch {
		return []
	}
}

func page_2_mock() -> [StargazersModel] {
	do {
		let models = try JSONDecoder().decode([StargazerRequestModel].self, from: page_2.data(using: .utf8)!)
		return models.map { (m: StargazerRequestModel) -> StargazersModel in
				let model = StargazersModel(
					name: m.login,
					imageUrl: URL(string: m.avatar_url)
				)
				
				return model
			}
	} catch {
		return []
	}
}

func page_3_mock() -> [StargazersModel] {
	do {
		let models = try JSONDecoder().decode([StargazerRequestModel].self, from: page_3.data(using: .utf8)!)
		return models.map { (m: StargazerRequestModel) -> StargazersModel in
				let model = StargazersModel(
					name: m.login,
					imageUrl: URL(string: m.avatar_url)
				)
				
				return model
			}
	} catch {
		return []
	}
}

let page_1 = """
[
	{
		"login": "schacon",
		"id": 70,
		"node_id": "MDQ6VXNlcjcw",
		"avatar_url": "https://avatars.githubusercontent.com/u/70?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/schacon",
		"html_url": "https://github.com/schacon",
		"followers_url": "https://api.github.com/users/schacon/followers",
		"following_url": "https://api.github.com/users/schacon/following{/other_user}",
		"gists_url": "https://api.github.com/users/schacon/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/schacon/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/schacon/subscriptions",
		"organizations_url": "https://api.github.com/users/schacon/orgs",
		"repos_url": "https://api.github.com/users/schacon/repos",
		"events_url": "https://api.github.com/users/schacon/events{/privacy}",
		"received_events_url": "https://api.github.com/users/schacon/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "adelcambre",
		"id": 242,
		"node_id": "MDQ6VXNlcjI0Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/242?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/adelcambre",
		"html_url": "https://github.com/adelcambre",
		"followers_url": "https://api.github.com/users/adelcambre/followers",
		"following_url": "https://api.github.com/users/adelcambre/following{/other_user}",
		"gists_url": "https://api.github.com/users/adelcambre/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/adelcambre/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/adelcambre/subscriptions",
		"organizations_url": "https://api.github.com/users/adelcambre/orgs",
		"repos_url": "https://api.github.com/users/adelcambre/repos",
		"events_url": "https://api.github.com/users/adelcambre/events{/privacy}",
		"received_events_url": "https://api.github.com/users/adelcambre/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "usergenic",
		"id": 578,
		"node_id": "MDQ6VXNlcjU3OA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/578?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/usergenic",
		"html_url": "https://github.com/usergenic",
		"followers_url": "https://api.github.com/users/usergenic/followers",
		"following_url": "https://api.github.com/users/usergenic/following{/other_user}",
		"gists_url": "https://api.github.com/users/usergenic/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/usergenic/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/usergenic/subscriptions",
		"organizations_url": "https://api.github.com/users/usergenic/orgs",
		"repos_url": "https://api.github.com/users/usergenic/repos",
		"events_url": "https://api.github.com/users/usergenic/events{/privacy}",
		"received_events_url": "https://api.github.com/users/usergenic/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "fdb",
		"id": 8477,
		"node_id": "MDQ6VXNlcjg0Nzc=",
		"avatar_url": "https://avatars.githubusercontent.com/u/8477?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/fdb",
		"html_url": "https://github.com/fdb",
		"followers_url": "https://api.github.com/users/fdb/followers",
		"following_url": "https://api.github.com/users/fdb/following{/other_user}",
		"gists_url": "https://api.github.com/users/fdb/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/fdb/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/fdb/subscriptions",
		"organizations_url": "https://api.github.com/users/fdb/orgs",
		"repos_url": "https://api.github.com/users/fdb/repos",
		"events_url": "https://api.github.com/users/fdb/events{/privacy}",
		"received_events_url": "https://api.github.com/users/fdb/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "darinel",
		"id": 29478,
		"node_id": "MDQ6VXNlcjI5NDc4",
		"avatar_url": "https://avatars.githubusercontent.com/u/29478?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/darinel",
		"html_url": "https://github.com/darinel",
		"followers_url": "https://api.github.com/users/darinel/followers",
		"following_url": "https://api.github.com/users/darinel/following{/other_user}",
		"gists_url": "https://api.github.com/users/darinel/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/darinel/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/darinel/subscriptions",
		"organizations_url": "https://api.github.com/users/darinel/orgs",
		"repos_url": "https://api.github.com/users/darinel/repos",
		"events_url": "https://api.github.com/users/darinel/events{/privacy}",
		"received_events_url": "https://api.github.com/users/darinel/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "Willianvdv",
		"id": 102915,
		"node_id": "MDQ6VXNlcjEwMjkxNQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/102915?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Willianvdv",
		"html_url": "https://github.com/Willianvdv",
		"followers_url": "https://api.github.com/users/Willianvdv/followers",
		"following_url": "https://api.github.com/users/Willianvdv/following{/other_user}",
		"gists_url": "https://api.github.com/users/Willianvdv/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Willianvdv/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Willianvdv/subscriptions",
		"organizations_url": "https://api.github.com/users/Willianvdv/orgs",
		"repos_url": "https://api.github.com/users/Willianvdv/repos",
		"events_url": "https://api.github.com/users/Willianvdv/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Willianvdv/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "sul4bh",
		"id": 109486,
		"node_id": "MDQ6VXNlcjEwOTQ4Ng==",
		"avatar_url": "https://avatars.githubusercontent.com/u/109486?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/sul4bh",
		"html_url": "https://github.com/sul4bh",
		"followers_url": "https://api.github.com/users/sul4bh/followers",
		"following_url": "https://api.github.com/users/sul4bh/following{/other_user}",
		"gists_url": "https://api.github.com/users/sul4bh/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/sul4bh/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/sul4bh/subscriptions",
		"organizations_url": "https://api.github.com/users/sul4bh/orgs",
		"repos_url": "https://api.github.com/users/sul4bh/repos",
		"events_url": "https://api.github.com/users/sul4bh/events{/privacy}",
		"received_events_url": "https://api.github.com/users/sul4bh/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "preavy",
		"id": 131258,
		"node_id": "MDQ6VXNlcjEzMTI1OA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/131258?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/preavy",
		"html_url": "https://github.com/preavy",
		"followers_url": "https://api.github.com/users/preavy/followers",
		"following_url": "https://api.github.com/users/preavy/following{/other_user}",
		"gists_url": "https://api.github.com/users/preavy/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/preavy/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/preavy/subscriptions",
		"organizations_url": "https://api.github.com/users/preavy/orgs",
		"repos_url": "https://api.github.com/users/preavy/repos",
		"events_url": "https://api.github.com/users/preavy/events{/privacy}",
		"received_events_url": "https://api.github.com/users/preavy/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "benjic",
		"id": 135916,
		"node_id": "MDQ6VXNlcjEzNTkxNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/135916?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/benjic",
		"html_url": "https://github.com/benjic",
		"followers_url": "https://api.github.com/users/benjic/followers",
		"following_url": "https://api.github.com/users/benjic/following{/other_user}",
		"gists_url": "https://api.github.com/users/benjic/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/benjic/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/benjic/subscriptions",
		"organizations_url": "https://api.github.com/users/benjic/orgs",
		"repos_url": "https://api.github.com/users/benjic/repos",
		"events_url": "https://api.github.com/users/benjic/events{/privacy}",
		"received_events_url": "https://api.github.com/users/benjic/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hagiwaratakayuki",
		"id": 141513,
		"node_id": "MDQ6VXNlcjE0MTUxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/141513?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hagiwaratakayuki",
		"html_url": "https://github.com/hagiwaratakayuki",
		"followers_url": "https://api.github.com/users/hagiwaratakayuki/followers",
		"following_url": "https://api.github.com/users/hagiwaratakayuki/following{/other_user}",
		"gists_url": "https://api.github.com/users/hagiwaratakayuki/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hagiwaratakayuki/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hagiwaratakayuki/subscriptions",
		"organizations_url": "https://api.github.com/users/hagiwaratakayuki/orgs",
		"repos_url": "https://api.github.com/users/hagiwaratakayuki/repos",
		"events_url": "https://api.github.com/users/hagiwaratakayuki/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hagiwaratakayuki/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "stefanlasiewski",
		"id": 142752,
		"node_id": "MDQ6VXNlcjE0Mjc1Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/142752?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/stefanlasiewski",
		"html_url": "https://github.com/stefanlasiewski",
		"followers_url": "https://api.github.com/users/stefanlasiewski/followers",
		"following_url": "https://api.github.com/users/stefanlasiewski/following{/other_user}",
		"gists_url": "https://api.github.com/users/stefanlasiewski/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/stefanlasiewski/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/stefanlasiewski/subscriptions",
		"organizations_url": "https://api.github.com/users/stefanlasiewski/orgs",
		"repos_url": "https://api.github.com/users/stefanlasiewski/repos",
		"events_url": "https://api.github.com/users/stefanlasiewski/events{/privacy}",
		"received_events_url": "https://api.github.com/users/stefanlasiewski/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hbjerry",
		"id": 174603,
		"node_id": "MDQ6VXNlcjE3NDYwMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/174603?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hbjerry",
		"html_url": "https://github.com/hbjerry",
		"followers_url": "https://api.github.com/users/hbjerry/followers",
		"following_url": "https://api.github.com/users/hbjerry/following{/other_user}",
		"gists_url": "https://api.github.com/users/hbjerry/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hbjerry/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hbjerry/subscriptions",
		"organizations_url": "https://api.github.com/users/hbjerry/orgs",
		"repos_url": "https://api.github.com/users/hbjerry/repos",
		"events_url": "https://api.github.com/users/hbjerry/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hbjerry/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "Visgean",
		"id": 193832,
		"node_id": "MDQ6VXNlcjE5MzgzMg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/193832?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Visgean",
		"html_url": "https://github.com/Visgean",
		"followers_url": "https://api.github.com/users/Visgean/followers",
		"following_url": "https://api.github.com/users/Visgean/following{/other_user}",
		"gists_url": "https://api.github.com/users/Visgean/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Visgean/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Visgean/subscriptions",
		"organizations_url": "https://api.github.com/users/Visgean/orgs",
		"repos_url": "https://api.github.com/users/Visgean/repos",
		"events_url": "https://api.github.com/users/Visgean/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Visgean/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "jiska",
		"id": 210861,
		"node_id": "MDQ6VXNlcjIxMDg2MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/210861?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/jiska",
		"html_url": "https://github.com/jiska",
		"followers_url": "https://api.github.com/users/jiska/followers",
		"following_url": "https://api.github.com/users/jiska/following{/other_user}",
		"gists_url": "https://api.github.com/users/jiska/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/jiska/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/jiska/subscriptions",
		"organizations_url": "https://api.github.com/users/jiska/orgs",
		"repos_url": "https://api.github.com/users/jiska/repos",
		"events_url": "https://api.github.com/users/jiska/events{/privacy}",
		"received_events_url": "https://api.github.com/users/jiska/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hittudiv",
		"id": 236097,
		"node_id": "MDQ6VXNlcjIzNjA5Nw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/236097?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hittudiv",
		"html_url": "https://github.com/hittudiv",
		"followers_url": "https://api.github.com/users/hittudiv/followers",
		"following_url": "https://api.github.com/users/hittudiv/following{/other_user}",
		"gists_url": "https://api.github.com/users/hittudiv/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hittudiv/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hittudiv/subscriptions",
		"organizations_url": "https://api.github.com/users/hittudiv/orgs",
		"repos_url": "https://api.github.com/users/hittudiv/repos",
		"events_url": "https://api.github.com/users/hittudiv/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hittudiv/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "paulomichael",
		"id": 237418,
		"node_id": "MDQ6VXNlcjIzNzQxOA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/237418?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/paulomichael",
		"html_url": "https://github.com/paulomichael",
		"followers_url": "https://api.github.com/users/paulomichael/followers",
		"following_url": "https://api.github.com/users/paulomichael/following{/other_user}",
		"gists_url": "https://api.github.com/users/paulomichael/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/paulomichael/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/paulomichael/subscriptions",
		"organizations_url": "https://api.github.com/users/paulomichael/orgs",
		"repos_url": "https://api.github.com/users/paulomichael/repos",
		"events_url": "https://api.github.com/users/paulomichael/events{/privacy}",
		"received_events_url": "https://api.github.com/users/paulomichael/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "garbagemonster",
		"id": 243775,
		"node_id": "MDQ6VXNlcjI0Mzc3NQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/243775?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/garbagemonster",
		"html_url": "https://github.com/garbagemonster",
		"followers_url": "https://api.github.com/users/garbagemonster/followers",
		"following_url": "https://api.github.com/users/garbagemonster/following{/other_user}",
		"gists_url": "https://api.github.com/users/garbagemonster/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/garbagemonster/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/garbagemonster/subscriptions",
		"organizations_url": "https://api.github.com/users/garbagemonster/orgs",
		"repos_url": "https://api.github.com/users/garbagemonster/repos",
		"events_url": "https://api.github.com/users/garbagemonster/events{/privacy}",
		"received_events_url": "https://api.github.com/users/garbagemonster/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "minamipj9",
		"id": 243983,
		"node_id": "MDQ6VXNlcjI0Mzk4Mw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/243983?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/minamipj9",
		"html_url": "https://github.com/minamipj9",
		"followers_url": "https://api.github.com/users/minamipj9/followers",
		"following_url": "https://api.github.com/users/minamipj9/following{/other_user}",
		"gists_url": "https://api.github.com/users/minamipj9/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/minamipj9/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/minamipj9/subscriptions",
		"organizations_url": "https://api.github.com/users/minamipj9/orgs",
		"repos_url": "https://api.github.com/users/minamipj9/repos",
		"events_url": "https://api.github.com/users/minamipj9/events{/privacy}",
		"received_events_url": "https://api.github.com/users/minamipj9/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "coolhead",
		"id": 245313,
		"node_id": "MDQ6VXNlcjI0NTMxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/245313?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/coolhead",
		"html_url": "https://github.com/coolhead",
		"followers_url": "https://api.github.com/users/coolhead/followers",
		"following_url": "https://api.github.com/users/coolhead/following{/other_user}",
		"gists_url": "https://api.github.com/users/coolhead/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/coolhead/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/coolhead/subscriptions",
		"organizations_url": "https://api.github.com/users/coolhead/orgs",
		"repos_url": "https://api.github.com/users/coolhead/repos",
		"events_url": "https://api.github.com/users/coolhead/events{/privacy}",
		"received_events_url": "https://api.github.com/users/coolhead/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "Spaceghost",
		"id": 251370,
		"node_id": "MDQ6VXNlcjI1MTM3MA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/251370?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/Spaceghost",
		"html_url": "https://github.com/Spaceghost",
		"followers_url": "https://api.github.com/users/Spaceghost/followers",
		"following_url": "https://api.github.com/users/Spaceghost/following{/other_user}",
		"gists_url": "https://api.github.com/users/Spaceghost/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/Spaceghost/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/Spaceghost/subscriptions",
		"organizations_url": "https://api.github.com/users/Spaceghost/orgs",
		"repos_url": "https://api.github.com/users/Spaceghost/repos",
		"events_url": "https://api.github.com/users/Spaceghost/events{/privacy}",
		"received_events_url": "https://api.github.com/users/Spaceghost/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "RustyF",
		"id": 277341,
		"node_id": "MDQ6VXNlcjI3NzM0MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/277341?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/RustyF",
		"html_url": "https://github.com/RustyF",
		"followers_url": "https://api.github.com/users/RustyF/followers",
		"following_url": "https://api.github.com/users/RustyF/following{/other_user}",
		"gists_url": "https://api.github.com/users/RustyF/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/RustyF/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/RustyF/subscriptions",
		"organizations_url": "https://api.github.com/users/RustyF/orgs",
		"repos_url": "https://api.github.com/users/RustyF/repos",
		"events_url": "https://api.github.com/users/RustyF/events{/privacy}",
		"received_events_url": "https://api.github.com/users/RustyF/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "chexee",
		"id": 285836,
		"node_id": "MDQ6VXNlcjI4NTgzNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/285836?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/chexee",
		"html_url": "https://github.com/chexee",
		"followers_url": "https://api.github.com/users/chexee/followers",
		"following_url": "https://api.github.com/users/chexee/following{/other_user}",
		"gists_url": "https://api.github.com/users/chexee/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/chexee/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/chexee/subscriptions",
		"organizations_url": "https://api.github.com/users/chexee/orgs",
		"repos_url": "https://api.github.com/users/chexee/repos",
		"events_url": "https://api.github.com/users/chexee/events{/privacy}",
		"received_events_url": "https://api.github.com/users/chexee/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "adrianbarbic",
		"id": 296263,
		"node_id": "MDQ6VXNlcjI5NjI2Mw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/296263?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/adrianbarbic",
		"html_url": "https://github.com/adrianbarbic",
		"followers_url": "https://api.github.com/users/adrianbarbic/followers",
		"following_url": "https://api.github.com/users/adrianbarbic/following{/other_user}",
		"gists_url": "https://api.github.com/users/adrianbarbic/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/adrianbarbic/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/adrianbarbic/subscriptions",
		"organizations_url": "https://api.github.com/users/adrianbarbic/orgs",
		"repos_url": "https://api.github.com/users/adrianbarbic/repos",
		"events_url": "https://api.github.com/users/adrianbarbic/events{/privacy}",
		"received_events_url": "https://api.github.com/users/adrianbarbic/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "yasirmturk",
		"id": 306691,
		"node_id": "MDQ6VXNlcjMwNjY5MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/306691?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/yasirmturk",
		"html_url": "https://github.com/yasirmturk",
		"followers_url": "https://api.github.com/users/yasirmturk/followers",
		"following_url": "https://api.github.com/users/yasirmturk/following{/other_user}",
		"gists_url": "https://api.github.com/users/yasirmturk/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/yasirmturk/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/yasirmturk/subscriptions",
		"organizations_url": "https://api.github.com/users/yasirmturk/orgs",
		"repos_url": "https://api.github.com/users/yasirmturk/repos",
		"events_url": "https://api.github.com/users/yasirmturk/events{/privacy}",
		"received_events_url": "https://api.github.com/users/yasirmturk/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "moonshadows",
		"id": 313279,
		"node_id": "MDQ6VXNlcjMxMzI3OQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/313279?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/moonshadows",
		"html_url": "https://github.com/moonshadows",
		"followers_url": "https://api.github.com/users/moonshadows/followers",
		"following_url": "https://api.github.com/users/moonshadows/following{/other_user}",
		"gists_url": "https://api.github.com/users/moonshadows/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/moonshadows/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/moonshadows/subscriptions",
		"organizations_url": "https://api.github.com/users/moonshadows/orgs",
		"repos_url": "https://api.github.com/users/moonshadows/repos",
		"events_url": "https://api.github.com/users/moonshadows/events{/privacy}",
		"received_events_url": "https://api.github.com/users/moonshadows/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "ff6347",
		"id": 315106,
		"node_id": "MDQ6VXNlcjMxNTEwNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/315106?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/ff6347",
		"html_url": "https://github.com/ff6347",
		"followers_url": "https://api.github.com/users/ff6347/followers",
		"following_url": "https://api.github.com/users/ff6347/following{/other_user}",
		"gists_url": "https://api.github.com/users/ff6347/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ff6347/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ff6347/subscriptions",
		"organizations_url": "https://api.github.com/users/ff6347/orgs",
		"repos_url": "https://api.github.com/users/ff6347/repos",
		"events_url": "https://api.github.com/users/ff6347/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ff6347/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "LunaticNeko",
		"id": 327290,
		"node_id": "MDQ6VXNlcjMyNzI5MA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/327290?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/LunaticNeko",
		"html_url": "https://github.com/LunaticNeko",
		"followers_url": "https://api.github.com/users/LunaticNeko/followers",
		"following_url": "https://api.github.com/users/LunaticNeko/following{/other_user}",
		"gists_url": "https://api.github.com/users/LunaticNeko/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/LunaticNeko/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/LunaticNeko/subscriptions",
		"organizations_url": "https://api.github.com/users/LunaticNeko/orgs",
		"repos_url": "https://api.github.com/users/LunaticNeko/repos",
		"events_url": "https://api.github.com/users/LunaticNeko/events{/privacy}",
		"received_events_url": "https://api.github.com/users/LunaticNeko/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "saadrehman",
		"id": 338472,
		"node_id": "MDQ6VXNlcjMzODQ3Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/338472?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/saadrehman",
		"html_url": "https://github.com/saadrehman",
		"followers_url": "https://api.github.com/users/saadrehman/followers",
		"following_url": "https://api.github.com/users/saadrehman/following{/other_user}",
		"gists_url": "https://api.github.com/users/saadrehman/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/saadrehman/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/saadrehman/subscriptions",
		"organizations_url": "https://api.github.com/users/saadrehman/orgs",
		"repos_url": "https://api.github.com/users/saadrehman/repos",
		"events_url": "https://api.github.com/users/saadrehman/events{/privacy}",
		"received_events_url": "https://api.github.com/users/saadrehman/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "allanmaio",
		"id": 345807,
		"node_id": "MDQ6VXNlcjM0NTgwNw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/345807?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/allanmaio",
		"html_url": "https://github.com/allanmaio",
		"followers_url": "https://api.github.com/users/allanmaio/followers",
		"following_url": "https://api.github.com/users/allanmaio/following{/other_user}",
		"gists_url": "https://api.github.com/users/allanmaio/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/allanmaio/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/allanmaio/subscriptions",
		"organizations_url": "https://api.github.com/users/allanmaio/orgs",
		"repos_url": "https://api.github.com/users/allanmaio/repos",
		"events_url": "https://api.github.com/users/allanmaio/events{/privacy}",
		"received_events_url": "https://api.github.com/users/allanmaio/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "kapare",
		"id": 349579,
		"node_id": "MDQ6VXNlcjM0OTU3OQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/349579?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/kapare",
		"html_url": "https://github.com/kapare",
		"followers_url": "https://api.github.com/users/kapare/followers",
		"following_url": "https://api.github.com/users/kapare/following{/other_user}",
		"gists_url": "https://api.github.com/users/kapare/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/kapare/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/kapare/subscriptions",
		"organizations_url": "https://api.github.com/users/kapare/orgs",
		"repos_url": "https://api.github.com/users/kapare/repos",
		"events_url": "https://api.github.com/users/kapare/events{/privacy}",
		"received_events_url": "https://api.github.com/users/kapare/received_events",
		"type": "User",
		"site_admin": false
	}
]
"""

let page_2 = """
[
	{
		"login": "kjaikeerthi",
		"id": 351510,
		"node_id": "MDQ6VXNlcjM1MTUxMA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/351510?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/kjaikeerthi",
		"html_url": "https://github.com/kjaikeerthi",
		"followers_url": "https://api.github.com/users/kjaikeerthi/followers",
		"following_url": "https://api.github.com/users/kjaikeerthi/following{/other_user}",
		"gists_url": "https://api.github.com/users/kjaikeerthi/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/kjaikeerthi/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/kjaikeerthi/subscriptions",
		"organizations_url": "https://api.github.com/users/kjaikeerthi/orgs",
		"repos_url": "https://api.github.com/users/kjaikeerthi/repos",
		"events_url": "https://api.github.com/users/kjaikeerthi/events{/privacy}",
		"received_events_url": "https://api.github.com/users/kjaikeerthi/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "TheFox",
		"id": 353709,
		"node_id": "MDQ6VXNlcjM1MzcwOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/353709?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/TheFox",
		"html_url": "https://github.com/TheFox",
		"followers_url": "https://api.github.com/users/TheFox/followers",
		"following_url": "https://api.github.com/users/TheFox/following{/other_user}",
		"gists_url": "https://api.github.com/users/TheFox/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/TheFox/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/TheFox/subscriptions",
		"organizations_url": "https://api.github.com/users/TheFox/orgs",
		"repos_url": "https://api.github.com/users/TheFox/repos",
		"events_url": "https://api.github.com/users/TheFox/events{/privacy}",
		"received_events_url": "https://api.github.com/users/TheFox/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "farhang",
		"id": 363150,
		"node_id": "MDQ6VXNlcjM2MzE1MA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/363150?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/farhang",
		"html_url": "https://github.com/farhang",
		"followers_url": "https://api.github.com/users/farhang/followers",
		"following_url": "https://api.github.com/users/farhang/following{/other_user}",
		"gists_url": "https://api.github.com/users/farhang/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/farhang/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/farhang/subscriptions",
		"organizations_url": "https://api.github.com/users/farhang/orgs",
		"repos_url": "https://api.github.com/users/farhang/repos",
		"events_url": "https://api.github.com/users/farhang/events{/privacy}",
		"received_events_url": "https://api.github.com/users/farhang/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "jiqihuman",
		"id": 370387,
		"node_id": "MDQ6VXNlcjM3MDM4Nw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/370387?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/jiqihuman",
		"html_url": "https://github.com/jiqihuman",
		"followers_url": "https://api.github.com/users/jiqihuman/followers",
		"following_url": "https://api.github.com/users/jiqihuman/following{/other_user}",
		"gists_url": "https://api.github.com/users/jiqihuman/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/jiqihuman/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/jiqihuman/subscriptions",
		"organizations_url": "https://api.github.com/users/jiqihuman/orgs",
		"repos_url": "https://api.github.com/users/jiqihuman/repos",
		"events_url": "https://api.github.com/users/jiqihuman/events{/privacy}",
		"received_events_url": "https://api.github.com/users/jiqihuman/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "chrislatimer1",
		"id": 371310,
		"node_id": "MDQ6VXNlcjM3MTMxMA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/371310?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/chrislatimer1",
		"html_url": "https://github.com/chrislatimer1",
		"followers_url": "https://api.github.com/users/chrislatimer1/followers",
		"following_url": "https://api.github.com/users/chrislatimer1/following{/other_user}",
		"gists_url": "https://api.github.com/users/chrislatimer1/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/chrislatimer1/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/chrislatimer1/subscriptions",
		"organizations_url": "https://api.github.com/users/chrislatimer1/orgs",
		"repos_url": "https://api.github.com/users/chrislatimer1/repos",
		"events_url": "https://api.github.com/users/chrislatimer1/events{/privacy}",
		"received_events_url": "https://api.github.com/users/chrislatimer1/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "chrisbelyea",
		"id": 387922,
		"node_id": "MDQ6VXNlcjM4NzkyMg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/387922?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/chrisbelyea",
		"html_url": "https://github.com/chrisbelyea",
		"followers_url": "https://api.github.com/users/chrisbelyea/followers",
		"following_url": "https://api.github.com/users/chrisbelyea/following{/other_user}",
		"gists_url": "https://api.github.com/users/chrisbelyea/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/chrisbelyea/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/chrisbelyea/subscriptions",
		"organizations_url": "https://api.github.com/users/chrisbelyea/orgs",
		"repos_url": "https://api.github.com/users/chrisbelyea/repos",
		"events_url": "https://api.github.com/users/chrisbelyea/events{/privacy}",
		"received_events_url": "https://api.github.com/users/chrisbelyea/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "josuesasilva",
		"id": 390852,
		"node_id": "MDQ6VXNlcjM5MDg1Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/390852?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/josuesasilva",
		"html_url": "https://github.com/josuesasilva",
		"followers_url": "https://api.github.com/users/josuesasilva/followers",
		"following_url": "https://api.github.com/users/josuesasilva/following{/other_user}",
		"gists_url": "https://api.github.com/users/josuesasilva/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/josuesasilva/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/josuesasilva/subscriptions",
		"organizations_url": "https://api.github.com/users/josuesasilva/orgs",
		"repos_url": "https://api.github.com/users/josuesasilva/repos",
		"events_url": "https://api.github.com/users/josuesasilva/events{/privacy}",
		"received_events_url": "https://api.github.com/users/josuesasilva/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "BedlamB",
		"id": 392331,
		"node_id": "MDQ6VXNlcjM5MjMzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/392331?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/BedlamB",
		"html_url": "https://github.com/BedlamB",
		"followers_url": "https://api.github.com/users/BedlamB/followers",
		"following_url": "https://api.github.com/users/BedlamB/following{/other_user}",
		"gists_url": "https://api.github.com/users/BedlamB/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/BedlamB/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/BedlamB/subscriptions",
		"organizations_url": "https://api.github.com/users/BedlamB/orgs",
		"repos_url": "https://api.github.com/users/BedlamB/repos",
		"events_url": "https://api.github.com/users/BedlamB/events{/privacy}",
		"received_events_url": "https://api.github.com/users/BedlamB/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "NeutralAngel",
		"id": 396876,
		"node_id": "MDQ6VXNlcjM5Njg3Ng==",
		"avatar_url": "https://avatars.githubusercontent.com/u/396876?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/NeutralAngel",
		"html_url": "https://github.com/NeutralAngel",
		"followers_url": "https://api.github.com/users/NeutralAngel/followers",
		"following_url": "https://api.github.com/users/NeutralAngel/following{/other_user}",
		"gists_url": "https://api.github.com/users/NeutralAngel/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/NeutralAngel/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/NeutralAngel/subscriptions",
		"organizations_url": "https://api.github.com/users/NeutralAngel/orgs",
		"repos_url": "https://api.github.com/users/NeutralAngel/repos",
		"events_url": "https://api.github.com/users/NeutralAngel/events{/privacy}",
		"received_events_url": "https://api.github.com/users/NeutralAngel/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "laschweinski",
		"id": 399687,
		"node_id": "MDQ6VXNlcjM5OTY4Nw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/399687?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/laschweinski",
		"html_url": "https://github.com/laschweinski",
		"followers_url": "https://api.github.com/users/laschweinski/followers",
		"following_url": "https://api.github.com/users/laschweinski/following{/other_user}",
		"gists_url": "https://api.github.com/users/laschweinski/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/laschweinski/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/laschweinski/subscriptions",
		"organizations_url": "https://api.github.com/users/laschweinski/orgs",
		"repos_url": "https://api.github.com/users/laschweinski/repos",
		"events_url": "https://api.github.com/users/laschweinski/events{/privacy}",
		"received_events_url": "https://api.github.com/users/laschweinski/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "yhippa",
		"id": 420309,
		"node_id": "MDQ6VXNlcjQyMDMwOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/420309?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/yhippa",
		"html_url": "https://github.com/yhippa",
		"followers_url": "https://api.github.com/users/yhippa/followers",
		"following_url": "https://api.github.com/users/yhippa/following{/other_user}",
		"gists_url": "https://api.github.com/users/yhippa/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/yhippa/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/yhippa/subscriptions",
		"organizations_url": "https://api.github.com/users/yhippa/orgs",
		"repos_url": "https://api.github.com/users/yhippa/repos",
		"events_url": "https://api.github.com/users/yhippa/events{/privacy}",
		"received_events_url": "https://api.github.com/users/yhippa/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "korrawit",
		"id": 459124,
		"node_id": "MDQ6VXNlcjQ1OTEyNA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/459124?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/korrawit",
		"html_url": "https://github.com/korrawit",
		"followers_url": "https://api.github.com/users/korrawit/followers",
		"following_url": "https://api.github.com/users/korrawit/following{/other_user}",
		"gists_url": "https://api.github.com/users/korrawit/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/korrawit/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/korrawit/subscriptions",
		"organizations_url": "https://api.github.com/users/korrawit/orgs",
		"repos_url": "https://api.github.com/users/korrawit/repos",
		"events_url": "https://api.github.com/users/korrawit/events{/privacy}",
		"received_events_url": "https://api.github.com/users/korrawit/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "clwang",
		"id": 459714,
		"node_id": "MDQ6VXNlcjQ1OTcxNA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/459714?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/clwang",
		"html_url": "https://github.com/clwang",
		"followers_url": "https://api.github.com/users/clwang/followers",
		"following_url": "https://api.github.com/users/clwang/following{/other_user}",
		"gists_url": "https://api.github.com/users/clwang/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/clwang/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/clwang/subscriptions",
		"organizations_url": "https://api.github.com/users/clwang/orgs",
		"repos_url": "https://api.github.com/users/clwang/repos",
		"events_url": "https://api.github.com/users/clwang/events{/privacy}",
		"received_events_url": "https://api.github.com/users/clwang/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "claytonbench",
		"id": 468061,
		"node_id": "MDQ6VXNlcjQ2ODA2MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/468061?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/claytonbench",
		"html_url": "https://github.com/claytonbench",
		"followers_url": "https://api.github.com/users/claytonbench/followers",
		"following_url": "https://api.github.com/users/claytonbench/following{/other_user}",
		"gists_url": "https://api.github.com/users/claytonbench/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/claytonbench/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/claytonbench/subscriptions",
		"organizations_url": "https://api.github.com/users/claytonbench/orgs",
		"repos_url": "https://api.github.com/users/claytonbench/repos",
		"events_url": "https://api.github.com/users/claytonbench/events{/privacy}",
		"received_events_url": "https://api.github.com/users/claytonbench/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "inspiration",
		"id": 475262,
		"node_id": "MDQ6VXNlcjQ3NTI2Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/475262?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/inspiration",
		"html_url": "https://github.com/inspiration",
		"followers_url": "https://api.github.com/users/inspiration/followers",
		"following_url": "https://api.github.com/users/inspiration/following{/other_user}",
		"gists_url": "https://api.github.com/users/inspiration/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/inspiration/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/inspiration/subscriptions",
		"organizations_url": "https://api.github.com/users/inspiration/orgs",
		"repos_url": "https://api.github.com/users/inspiration/repos",
		"events_url": "https://api.github.com/users/inspiration/events{/privacy}",
		"received_events_url": "https://api.github.com/users/inspiration/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "rotaris",
		"id": 476871,
		"node_id": "MDQ6VXNlcjQ3Njg3MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/476871?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/rotaris",
		"html_url": "https://github.com/rotaris",
		"followers_url": "https://api.github.com/users/rotaris/followers",
		"following_url": "https://api.github.com/users/rotaris/following{/other_user}",
		"gists_url": "https://api.github.com/users/rotaris/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/rotaris/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/rotaris/subscriptions",
		"organizations_url": "https://api.github.com/users/rotaris/orgs",
		"repos_url": "https://api.github.com/users/rotaris/repos",
		"events_url": "https://api.github.com/users/rotaris/events{/privacy}",
		"received_events_url": "https://api.github.com/users/rotaris/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "henkisdabro",
		"id": 477513,
		"node_id": "MDQ6VXNlcjQ3NzUxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/477513?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/henkisdabro",
		"html_url": "https://github.com/henkisdabro",
		"followers_url": "https://api.github.com/users/henkisdabro/followers",
		"following_url": "https://api.github.com/users/henkisdabro/following{/other_user}",
		"gists_url": "https://api.github.com/users/henkisdabro/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/henkisdabro/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/henkisdabro/subscriptions",
		"organizations_url": "https://api.github.com/users/henkisdabro/orgs",
		"repos_url": "https://api.github.com/users/henkisdabro/repos",
		"events_url": "https://api.github.com/users/henkisdabro/events{/privacy}",
		"received_events_url": "https://api.github.com/users/henkisdabro/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "e2kaneko",
		"id": 480139,
		"node_id": "MDQ6VXNlcjQ4MDEzOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/480139?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/e2kaneko",
		"html_url": "https://github.com/e2kaneko",
		"followers_url": "https://api.github.com/users/e2kaneko/followers",
		"following_url": "https://api.github.com/users/e2kaneko/following{/other_user}",
		"gists_url": "https://api.github.com/users/e2kaneko/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/e2kaneko/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/e2kaneko/subscriptions",
		"organizations_url": "https://api.github.com/users/e2kaneko/orgs",
		"repos_url": "https://api.github.com/users/e2kaneko/repos",
		"events_url": "https://api.github.com/users/e2kaneko/events{/privacy}",
		"received_events_url": "https://api.github.com/users/e2kaneko/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "joshp1",
		"id": 481110,
		"node_id": "MDQ6VXNlcjQ4MTExMA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/481110?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/joshp1",
		"html_url": "https://github.com/joshp1",
		"followers_url": "https://api.github.com/users/joshp1/followers",
		"following_url": "https://api.github.com/users/joshp1/following{/other_user}",
		"gists_url": "https://api.github.com/users/joshp1/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/joshp1/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/joshp1/subscriptions",
		"organizations_url": "https://api.github.com/users/joshp1/orgs",
		"repos_url": "https://api.github.com/users/joshp1/repos",
		"events_url": "https://api.github.com/users/joshp1/events{/privacy}",
		"received_events_url": "https://api.github.com/users/joshp1/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "mqmtech",
		"id": 487274,
		"node_id": "MDQ6VXNlcjQ4NzI3NA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/487274?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/mqmtech",
		"html_url": "https://github.com/mqmtech",
		"followers_url": "https://api.github.com/users/mqmtech/followers",
		"following_url": "https://api.github.com/users/mqmtech/following{/other_user}",
		"gists_url": "https://api.github.com/users/mqmtech/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/mqmtech/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/mqmtech/subscriptions",
		"organizations_url": "https://api.github.com/users/mqmtech/orgs",
		"repos_url": "https://api.github.com/users/mqmtech/repos",
		"events_url": "https://api.github.com/users/mqmtech/events{/privacy}",
		"received_events_url": "https://api.github.com/users/mqmtech/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "zankyr",
		"id": 503447,
		"node_id": "MDQ6VXNlcjUwMzQ0Nw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/503447?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/zankyr",
		"html_url": "https://github.com/zankyr",
		"followers_url": "https://api.github.com/users/zankyr/followers",
		"following_url": "https://api.github.com/users/zankyr/following{/other_user}",
		"gists_url": "https://api.github.com/users/zankyr/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/zankyr/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/zankyr/subscriptions",
		"organizations_url": "https://api.github.com/users/zankyr/orgs",
		"repos_url": "https://api.github.com/users/zankyr/repos",
		"events_url": "https://api.github.com/users/zankyr/events{/privacy}",
		"received_events_url": "https://api.github.com/users/zankyr/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "rnowotniak",
		"id": 503834,
		"node_id": "MDQ6VXNlcjUwMzgzNA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/503834?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/rnowotniak",
		"html_url": "https://github.com/rnowotniak",
		"followers_url": "https://api.github.com/users/rnowotniak/followers",
		"following_url": "https://api.github.com/users/rnowotniak/following{/other_user}",
		"gists_url": "https://api.github.com/users/rnowotniak/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/rnowotniak/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/rnowotniak/subscriptions",
		"organizations_url": "https://api.github.com/users/rnowotniak/orgs",
		"repos_url": "https://api.github.com/users/rnowotniak/repos",
		"events_url": "https://api.github.com/users/rnowotniak/events{/privacy}",
		"received_events_url": "https://api.github.com/users/rnowotniak/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hpointu",
		"id": 503906,
		"node_id": "MDQ6VXNlcjUwMzkwNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/503906?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hpointu",
		"html_url": "https://github.com/hpointu",
		"followers_url": "https://api.github.com/users/hpointu/followers",
		"following_url": "https://api.github.com/users/hpointu/following{/other_user}",
		"gists_url": "https://api.github.com/users/hpointu/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hpointu/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hpointu/subscriptions",
		"organizations_url": "https://api.github.com/users/hpointu/orgs",
		"repos_url": "https://api.github.com/users/hpointu/repos",
		"events_url": "https://api.github.com/users/hpointu/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hpointu/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "BourneID",
		"id": 517431,
		"node_id": "MDQ6VXNlcjUxNzQzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/517431?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/BourneID",
		"html_url": "https://github.com/BourneID",
		"followers_url": "https://api.github.com/users/BourneID/followers",
		"following_url": "https://api.github.com/users/BourneID/following{/other_user}",
		"gists_url": "https://api.github.com/users/BourneID/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/BourneID/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/BourneID/subscriptions",
		"organizations_url": "https://api.github.com/users/BourneID/orgs",
		"repos_url": "https://api.github.com/users/BourneID/repos",
		"events_url": "https://api.github.com/users/BourneID/events{/privacy}",
		"received_events_url": "https://api.github.com/users/BourneID/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "am-cornelis",
		"id": 517959,
		"node_id": "MDQ6VXNlcjUxNzk1OQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/517959?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/am-cornelis",
		"html_url": "https://github.com/am-cornelis",
		"followers_url": "https://api.github.com/users/am-cornelis/followers",
		"following_url": "https://api.github.com/users/am-cornelis/following{/other_user}",
		"gists_url": "https://api.github.com/users/am-cornelis/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/am-cornelis/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/am-cornelis/subscriptions",
		"organizations_url": "https://api.github.com/users/am-cornelis/orgs",
		"repos_url": "https://api.github.com/users/am-cornelis/repos",
		"events_url": "https://api.github.com/users/am-cornelis/events{/privacy}",
		"received_events_url": "https://api.github.com/users/am-cornelis/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "joelklee",
		"id": 520544,
		"node_id": "MDQ6VXNlcjUyMDU0NA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/520544?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/joelklee",
		"html_url": "https://github.com/joelklee",
		"followers_url": "https://api.github.com/users/joelklee/followers",
		"following_url": "https://api.github.com/users/joelklee/following{/other_user}",
		"gists_url": "https://api.github.com/users/joelklee/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/joelklee/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/joelklee/subscriptions",
		"organizations_url": "https://api.github.com/users/joelklee/orgs",
		"repos_url": "https://api.github.com/users/joelklee/repos",
		"events_url": "https://api.github.com/users/joelklee/events{/privacy}",
		"received_events_url": "https://api.github.com/users/joelklee/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "chnlkw",
		"id": 536313,
		"node_id": "MDQ6VXNlcjUzNjMxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/536313?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/chnlkw",
		"html_url": "https://github.com/chnlkw",
		"followers_url": "https://api.github.com/users/chnlkw/followers",
		"following_url": "https://api.github.com/users/chnlkw/following{/other_user}",
		"gists_url": "https://api.github.com/users/chnlkw/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/chnlkw/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/chnlkw/subscriptions",
		"organizations_url": "https://api.github.com/users/chnlkw/orgs",
		"repos_url": "https://api.github.com/users/chnlkw/repos",
		"events_url": "https://api.github.com/users/chnlkw/events{/privacy}",
		"received_events_url": "https://api.github.com/users/chnlkw/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "fuho",
		"id": 539452,
		"node_id": "MDQ6VXNlcjUzOTQ1Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/539452?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/fuho",
		"html_url": "https://github.com/fuho",
		"followers_url": "https://api.github.com/users/fuho/followers",
		"following_url": "https://api.github.com/users/fuho/following{/other_user}",
		"gists_url": "https://api.github.com/users/fuho/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/fuho/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/fuho/subscriptions",
		"organizations_url": "https://api.github.com/users/fuho/orgs",
		"repos_url": "https://api.github.com/users/fuho/repos",
		"events_url": "https://api.github.com/users/fuho/events{/privacy}",
		"received_events_url": "https://api.github.com/users/fuho/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "iamnilay3",
		"id": 546613,
		"node_id": "MDQ6VXNlcjU0NjYxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/546613?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/iamnilay3",
		"html_url": "https://github.com/iamnilay3",
		"followers_url": "https://api.github.com/users/iamnilay3/followers",
		"following_url": "https://api.github.com/users/iamnilay3/following{/other_user}",
		"gists_url": "https://api.github.com/users/iamnilay3/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/iamnilay3/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/iamnilay3/subscriptions",
		"organizations_url": "https://api.github.com/users/iamnilay3/orgs",
		"repos_url": "https://api.github.com/users/iamnilay3/repos",
		"events_url": "https://api.github.com/users/iamnilay3/events{/privacy}",
		"received_events_url": "https://api.github.com/users/iamnilay3/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "fcaraujo",
		"id": 553927,
		"node_id": "MDQ6VXNlcjU1MzkyNw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/553927?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/fcaraujo",
		"html_url": "https://github.com/fcaraujo",
		"followers_url": "https://api.github.com/users/fcaraujo/followers",
		"following_url": "https://api.github.com/users/fcaraujo/following{/other_user}",
		"gists_url": "https://api.github.com/users/fcaraujo/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/fcaraujo/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/fcaraujo/subscriptions",
		"organizations_url": "https://api.github.com/users/fcaraujo/orgs",
		"repos_url": "https://api.github.com/users/fcaraujo/repos",
		"events_url": "https://api.github.com/users/fcaraujo/events{/privacy}",
		"received_events_url": "https://api.github.com/users/fcaraujo/received_events",
		"type": "User",
		"site_admin": false
	}
]
"""

let page_3 = """
[
	{
		"login": "ryagas",
		"id": 553981,
		"node_id": "MDQ6VXNlcjU1Mzk4MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/553981?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/ryagas",
		"html_url": "https://github.com/ryagas",
		"followers_url": "https://api.github.com/users/ryagas/followers",
		"following_url": "https://api.github.com/users/ryagas/following{/other_user}",
		"gists_url": "https://api.github.com/users/ryagas/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ryagas/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ryagas/subscriptions",
		"organizations_url": "https://api.github.com/users/ryagas/orgs",
		"repos_url": "https://api.github.com/users/ryagas/repos",
		"events_url": "https://api.github.com/users/ryagas/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ryagas/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hydrogen2005",
		"id": 557010,
		"node_id": "MDQ6VXNlcjU1NzAxMA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/557010?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hydrogen2005",
		"html_url": "https://github.com/hydrogen2005",
		"followers_url": "https://api.github.com/users/hydrogen2005/followers",
		"following_url": "https://api.github.com/users/hydrogen2005/following{/other_user}",
		"gists_url": "https://api.github.com/users/hydrogen2005/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hydrogen2005/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hydrogen2005/subscriptions",
		"organizations_url": "https://api.github.com/users/hydrogen2005/orgs",
		"repos_url": "https://api.github.com/users/hydrogen2005/repos",
		"events_url": "https://api.github.com/users/hydrogen2005/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hydrogen2005/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "octocat",
		"id": 583231,
		"node_id": "MDQ6VXNlcjU4MzIzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/583231?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/octocat",
		"html_url": "https://github.com/octocat",
		"followers_url": "https://api.github.com/users/octocat/followers",
		"following_url": "https://api.github.com/users/octocat/following{/other_user}",
		"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
		"organizations_url": "https://api.github.com/users/octocat/orgs",
		"repos_url": "https://api.github.com/users/octocat/repos",
		"events_url": "https://api.github.com/users/octocat/events{/privacy}",
		"received_events_url": "https://api.github.com/users/octocat/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "lukemcnally84",
		"id": 583444,
		"node_id": "MDQ6VXNlcjU4MzQ0NA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/583444?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/lukemcnally84",
		"html_url": "https://github.com/lukemcnally84",
		"followers_url": "https://api.github.com/users/lukemcnally84/followers",
		"following_url": "https://api.github.com/users/lukemcnally84/following{/other_user}",
		"gists_url": "https://api.github.com/users/lukemcnally84/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/lukemcnally84/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/lukemcnally84/subscriptions",
		"organizations_url": "https://api.github.com/users/lukemcnally84/orgs",
		"repos_url": "https://api.github.com/users/lukemcnally84/repos",
		"events_url": "https://api.github.com/users/lukemcnally84/events{/privacy}",
		"received_events_url": "https://api.github.com/users/lukemcnally84/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "abhimit04",
		"id": 586662,
		"node_id": "MDQ6VXNlcjU4NjY2Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/586662?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/abhimit04",
		"html_url": "https://github.com/abhimit04",
		"followers_url": "https://api.github.com/users/abhimit04/followers",
		"following_url": "https://api.github.com/users/abhimit04/following{/other_user}",
		"gists_url": "https://api.github.com/users/abhimit04/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/abhimit04/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/abhimit04/subscriptions",
		"organizations_url": "https://api.github.com/users/abhimit04/orgs",
		"repos_url": "https://api.github.com/users/abhimit04/repos",
		"events_url": "https://api.github.com/users/abhimit04/events{/privacy}",
		"received_events_url": "https://api.github.com/users/abhimit04/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "warashina",
		"id": 598031,
		"node_id": "MDQ6VXNlcjU5ODAzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/598031?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/warashina",
		"html_url": "https://github.com/warashina",
		"followers_url": "https://api.github.com/users/warashina/followers",
		"following_url": "https://api.github.com/users/warashina/following{/other_user}",
		"gists_url": "https://api.github.com/users/warashina/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/warashina/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/warashina/subscriptions",
		"organizations_url": "https://api.github.com/users/warashina/orgs",
		"repos_url": "https://api.github.com/users/warashina/repos",
		"events_url": "https://api.github.com/users/warashina/events{/privacy}",
		"received_events_url": "https://api.github.com/users/warashina/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "marcinant",
		"id": 604561,
		"node_id": "MDQ6VXNlcjYwNDU2MQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/604561?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/marcinant",
		"html_url": "https://github.com/marcinant",
		"followers_url": "https://api.github.com/users/marcinant/followers",
		"following_url": "https://api.github.com/users/marcinant/following{/other_user}",
		"gists_url": "https://api.github.com/users/marcinant/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/marcinant/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/marcinant/subscriptions",
		"organizations_url": "https://api.github.com/users/marcinant/orgs",
		"repos_url": "https://api.github.com/users/marcinant/repos",
		"events_url": "https://api.github.com/users/marcinant/events{/privacy}",
		"received_events_url": "https://api.github.com/users/marcinant/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "flavionbc",
		"id": 605209,
		"node_id": "MDQ6VXNlcjYwNTIwOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/605209?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/flavionbc",
		"html_url": "https://github.com/flavionbc",
		"followers_url": "https://api.github.com/users/flavionbc/followers",
		"following_url": "https://api.github.com/users/flavionbc/following{/other_user}",
		"gists_url": "https://api.github.com/users/flavionbc/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/flavionbc/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/flavionbc/subscriptions",
		"organizations_url": "https://api.github.com/users/flavionbc/orgs",
		"repos_url": "https://api.github.com/users/flavionbc/repos",
		"events_url": "https://api.github.com/users/flavionbc/events{/privacy}",
		"received_events_url": "https://api.github.com/users/flavionbc/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "juhaelee",
		"id": 606411,
		"node_id": "MDQ6VXNlcjYwNjQxMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/606411?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/juhaelee",
		"html_url": "https://github.com/juhaelee",
		"followers_url": "https://api.github.com/users/juhaelee/followers",
		"following_url": "https://api.github.com/users/juhaelee/following{/other_user}",
		"gists_url": "https://api.github.com/users/juhaelee/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/juhaelee/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/juhaelee/subscriptions",
		"organizations_url": "https://api.github.com/users/juhaelee/orgs",
		"repos_url": "https://api.github.com/users/juhaelee/repos",
		"events_url": "https://api.github.com/users/juhaelee/events{/privacy}",
		"received_events_url": "https://api.github.com/users/juhaelee/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "mschoepf",
		"id": 608531,
		"node_id": "MDQ6VXNlcjYwODUzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/608531?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/mschoepf",
		"html_url": "https://github.com/mschoepf",
		"followers_url": "https://api.github.com/users/mschoepf/followers",
		"following_url": "https://api.github.com/users/mschoepf/following{/other_user}",
		"gists_url": "https://api.github.com/users/mschoepf/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/mschoepf/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/mschoepf/subscriptions",
		"organizations_url": "https://api.github.com/users/mschoepf/orgs",
		"repos_url": "https://api.github.com/users/mschoepf/repos",
		"events_url": "https://api.github.com/users/mschoepf/events{/privacy}",
		"received_events_url": "https://api.github.com/users/mschoepf/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "olamedia",
		"id": 611624,
		"node_id": "MDQ6VXNlcjYxMTYyNA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/611624?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/olamedia",
		"html_url": "https://github.com/olamedia",
		"followers_url": "https://api.github.com/users/olamedia/followers",
		"following_url": "https://api.github.com/users/olamedia/following{/other_user}",
		"gists_url": "https://api.github.com/users/olamedia/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/olamedia/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/olamedia/subscriptions",
		"organizations_url": "https://api.github.com/users/olamedia/orgs",
		"repos_url": "https://api.github.com/users/olamedia/repos",
		"events_url": "https://api.github.com/users/olamedia/events{/privacy}",
		"received_events_url": "https://api.github.com/users/olamedia/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "riichard",
		"id": 616976,
		"node_id": "MDQ6VXNlcjYxNjk3Ng==",
		"avatar_url": "https://avatars.githubusercontent.com/u/616976?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/riichard",
		"html_url": "https://github.com/riichard",
		"followers_url": "https://api.github.com/users/riichard/followers",
		"following_url": "https://api.github.com/users/riichard/following{/other_user}",
		"gists_url": "https://api.github.com/users/riichard/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/riichard/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/riichard/subscriptions",
		"organizations_url": "https://api.github.com/users/riichard/orgs",
		"repos_url": "https://api.github.com/users/riichard/repos",
		"events_url": "https://api.github.com/users/riichard/events{/privacy}",
		"received_events_url": "https://api.github.com/users/riichard/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "kangmin",
		"id": 621626,
		"node_id": "MDQ6VXNlcjYyMTYyNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/621626?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/kangmin",
		"html_url": "https://github.com/kangmin",
		"followers_url": "https://api.github.com/users/kangmin/followers",
		"following_url": "https://api.github.com/users/kangmin/following{/other_user}",
		"gists_url": "https://api.github.com/users/kangmin/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/kangmin/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/kangmin/subscriptions",
		"organizations_url": "https://api.github.com/users/kangmin/orgs",
		"repos_url": "https://api.github.com/users/kangmin/repos",
		"events_url": "https://api.github.com/users/kangmin/events{/privacy}",
		"received_events_url": "https://api.github.com/users/kangmin/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "moebious",
		"id": 624602,
		"node_id": "MDQ6VXNlcjYyNDYwMg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/624602?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/moebious",
		"html_url": "https://github.com/moebious",
		"followers_url": "https://api.github.com/users/moebious/followers",
		"following_url": "https://api.github.com/users/moebious/following{/other_user}",
		"gists_url": "https://api.github.com/users/moebious/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/moebious/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/moebious/subscriptions",
		"organizations_url": "https://api.github.com/users/moebious/orgs",
		"repos_url": "https://api.github.com/users/moebious/repos",
		"events_url": "https://api.github.com/users/moebious/events{/privacy}",
		"received_events_url": "https://api.github.com/users/moebious/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "siva001",
		"id": 627895,
		"node_id": "MDQ6VXNlcjYyNzg5NQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/627895?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/siva001",
		"html_url": "https://github.com/siva001",
		"followers_url": "https://api.github.com/users/siva001/followers",
		"following_url": "https://api.github.com/users/siva001/following{/other_user}",
		"gists_url": "https://api.github.com/users/siva001/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/siva001/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/siva001/subscriptions",
		"organizations_url": "https://api.github.com/users/siva001/orgs",
		"repos_url": "https://api.github.com/users/siva001/repos",
		"events_url": "https://api.github.com/users/siva001/events{/privacy}",
		"received_events_url": "https://api.github.com/users/siva001/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "MaxNanasy",
		"id": 628032,
		"node_id": "MDQ6VXNlcjYyODAzMg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/628032?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/MaxNanasy",
		"html_url": "https://github.com/MaxNanasy",
		"followers_url": "https://api.github.com/users/MaxNanasy/followers",
		"following_url": "https://api.github.com/users/MaxNanasy/following{/other_user}",
		"gists_url": "https://api.github.com/users/MaxNanasy/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/MaxNanasy/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/MaxNanasy/subscriptions",
		"organizations_url": "https://api.github.com/users/MaxNanasy/orgs",
		"repos_url": "https://api.github.com/users/MaxNanasy/repos",
		"events_url": "https://api.github.com/users/MaxNanasy/events{/privacy}",
		"received_events_url": "https://api.github.com/users/MaxNanasy/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "borsi",
		"id": 632613,
		"node_id": "MDQ6VXNlcjYzMjYxMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/632613?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/borsi",
		"html_url": "https://github.com/borsi",
		"followers_url": "https://api.github.com/users/borsi/followers",
		"following_url": "https://api.github.com/users/borsi/following{/other_user}",
		"gists_url": "https://api.github.com/users/borsi/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/borsi/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/borsi/subscriptions",
		"organizations_url": "https://api.github.com/users/borsi/orgs",
		"repos_url": "https://api.github.com/users/borsi/repos",
		"events_url": "https://api.github.com/users/borsi/events{/privacy}",
		"received_events_url": "https://api.github.com/users/borsi/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "youwannaknow",
		"id": 646452,
		"node_id": "MDQ6VXNlcjY0NjQ1Mg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/646452?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/youwannaknow",
		"html_url": "https://github.com/youwannaknow",
		"followers_url": "https://api.github.com/users/youwannaknow/followers",
		"following_url": "https://api.github.com/users/youwannaknow/following{/other_user}",
		"gists_url": "https://api.github.com/users/youwannaknow/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/youwannaknow/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/youwannaknow/subscriptions",
		"organizations_url": "https://api.github.com/users/youwannaknow/orgs",
		"repos_url": "https://api.github.com/users/youwannaknow/repos",
		"events_url": "https://api.github.com/users/youwannaknow/events{/privacy}",
		"received_events_url": "https://api.github.com/users/youwannaknow/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "fukuball",
		"id": 646843,
		"node_id": "MDQ6VXNlcjY0Njg0Mw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/646843?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/fukuball",
		"html_url": "https://github.com/fukuball",
		"followers_url": "https://api.github.com/users/fukuball/followers",
		"following_url": "https://api.github.com/users/fukuball/following{/other_user}",
		"gists_url": "https://api.github.com/users/fukuball/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/fukuball/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/fukuball/subscriptions",
		"organizations_url": "https://api.github.com/users/fukuball/orgs",
		"repos_url": "https://api.github.com/users/fukuball/repos",
		"events_url": "https://api.github.com/users/fukuball/events{/privacy}",
		"received_events_url": "https://api.github.com/users/fukuball/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "sai-manoj-kumar",
		"id": 647333,
		"node_id": "MDQ6VXNlcjY0NzMzMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/647333?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/sai-manoj-kumar",
		"html_url": "https://github.com/sai-manoj-kumar",
		"followers_url": "https://api.github.com/users/sai-manoj-kumar/followers",
		"following_url": "https://api.github.com/users/sai-manoj-kumar/following{/other_user}",
		"gists_url": "https://api.github.com/users/sai-manoj-kumar/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/sai-manoj-kumar/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/sai-manoj-kumar/subscriptions",
		"organizations_url": "https://api.github.com/users/sai-manoj-kumar/orgs",
		"repos_url": "https://api.github.com/users/sai-manoj-kumar/repos",
		"events_url": "https://api.github.com/users/sai-manoj-kumar/events{/privacy}",
		"received_events_url": "https://api.github.com/users/sai-manoj-kumar/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "CarsonGallo",
		"id": 648783,
		"node_id": "MDQ6VXNlcjY0ODc4Mw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/648783?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/CarsonGallo",
		"html_url": "https://github.com/CarsonGallo",
		"followers_url": "https://api.github.com/users/CarsonGallo/followers",
		"following_url": "https://api.github.com/users/CarsonGallo/following{/other_user}",
		"gists_url": "https://api.github.com/users/CarsonGallo/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/CarsonGallo/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/CarsonGallo/subscriptions",
		"organizations_url": "https://api.github.com/users/CarsonGallo/orgs",
		"repos_url": "https://api.github.com/users/CarsonGallo/repos",
		"events_url": "https://api.github.com/users/CarsonGallo/events{/privacy}",
		"received_events_url": "https://api.github.com/users/CarsonGallo/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "kwalker1977",
		"id": 651216,
		"node_id": "MDQ6VXNlcjY1MTIxNg==",
		"avatar_url": "https://avatars.githubusercontent.com/u/651216?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/kwalker1977",
		"html_url": "https://github.com/kwalker1977",
		"followers_url": "https://api.github.com/users/kwalker1977/followers",
		"following_url": "https://api.github.com/users/kwalker1977/following{/other_user}",
		"gists_url": "https://api.github.com/users/kwalker1977/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/kwalker1977/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/kwalker1977/subscriptions",
		"organizations_url": "https://api.github.com/users/kwalker1977/orgs",
		"repos_url": "https://api.github.com/users/kwalker1977/repos",
		"events_url": "https://api.github.com/users/kwalker1977/events{/privacy}",
		"received_events_url": "https://api.github.com/users/kwalker1977/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "anohmead",
		"id": 652487,
		"node_id": "MDQ6VXNlcjY1MjQ4Nw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/652487?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/anohmead",
		"html_url": "https://github.com/anohmead",
		"followers_url": "https://api.github.com/users/anohmead/followers",
		"following_url": "https://api.github.com/users/anohmead/following{/other_user}",
		"gists_url": "https://api.github.com/users/anohmead/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/anohmead/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/anohmead/subscriptions",
		"organizations_url": "https://api.github.com/users/anohmead/orgs",
		"repos_url": "https://api.github.com/users/anohmead/repos",
		"events_url": "https://api.github.com/users/anohmead/events{/privacy}",
		"received_events_url": "https://api.github.com/users/anohmead/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "drkirkland86",
		"id": 657003,
		"node_id": "MDQ6VXNlcjY1NzAwMw==",
		"avatar_url": "https://avatars.githubusercontent.com/u/657003?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/drkirkland86",
		"html_url": "https://github.com/drkirkland86",
		"followers_url": "https://api.github.com/users/drkirkland86/followers",
		"following_url": "https://api.github.com/users/drkirkland86/following{/other_user}",
		"gists_url": "https://api.github.com/users/drkirkland86/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/drkirkland86/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/drkirkland86/subscriptions",
		"organizations_url": "https://api.github.com/users/drkirkland86/orgs",
		"repos_url": "https://api.github.com/users/drkirkland86/repos",
		"events_url": "https://api.github.com/users/drkirkland86/events{/privacy}",
		"received_events_url": "https://api.github.com/users/drkirkland86/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "hyesushin",
		"id": 659539,
		"node_id": "MDQ6VXNlcjY1OTUzOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/659539?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/hyesushin",
		"html_url": "https://github.com/hyesushin",
		"followers_url": "https://api.github.com/users/hyesushin/followers",
		"following_url": "https://api.github.com/users/hyesushin/following{/other_user}",
		"gists_url": "https://api.github.com/users/hyesushin/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/hyesushin/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/hyesushin/subscriptions",
		"organizations_url": "https://api.github.com/users/hyesushin/orgs",
		"repos_url": "https://api.github.com/users/hyesushin/repos",
		"events_url": "https://api.github.com/users/hyesushin/events{/privacy}",
		"received_events_url": "https://api.github.com/users/hyesushin/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "mj001",
		"id": 660559,
		"node_id": "MDQ6VXNlcjY2MDU1OQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/660559?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/mj001",
		"html_url": "https://github.com/mj001",
		"followers_url": "https://api.github.com/users/mj001/followers",
		"following_url": "https://api.github.com/users/mj001/following{/other_user}",
		"gists_url": "https://api.github.com/users/mj001/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/mj001/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/mj001/subscriptions",
		"organizations_url": "https://api.github.com/users/mj001/orgs",
		"repos_url": "https://api.github.com/users/mj001/repos",
		"events_url": "https://api.github.com/users/mj001/events{/privacy}",
		"received_events_url": "https://api.github.com/users/mj001/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "yvo",
		"id": 662631,
		"node_id": "MDQ6VXNlcjY2MjYzMQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/662631?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/yvo",
		"html_url": "https://github.com/yvo",
		"followers_url": "https://api.github.com/users/yvo/followers",
		"following_url": "https://api.github.com/users/yvo/following{/other_user}",
		"gists_url": "https://api.github.com/users/yvo/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/yvo/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/yvo/subscriptions",
		"organizations_url": "https://api.github.com/users/yvo/orgs",
		"repos_url": "https://api.github.com/users/yvo/repos",
		"events_url": "https://api.github.com/users/yvo/events{/privacy}",
		"received_events_url": "https://api.github.com/users/yvo/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "sori",
		"id": 665404,
		"node_id": "MDQ6VXNlcjY2NTQwNA==",
		"avatar_url": "https://avatars.githubusercontent.com/u/665404?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/sori",
		"html_url": "https://github.com/sori",
		"followers_url": "https://api.github.com/users/sori/followers",
		"following_url": "https://api.github.com/users/sori/following{/other_user}",
		"gists_url": "https://api.github.com/users/sori/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/sori/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/sori/subscriptions",
		"organizations_url": "https://api.github.com/users/sori/orgs",
		"repos_url": "https://api.github.com/users/sori/repos",
		"events_url": "https://api.github.com/users/sori/events{/privacy}",
		"received_events_url": "https://api.github.com/users/sori/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "ngreader",
		"id": 666639,
		"node_id": "MDQ6VXNlcjY2NjYzOQ==",
		"avatar_url": "https://avatars.githubusercontent.com/u/666639?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/ngreader",
		"html_url": "https://github.com/ngreader",
		"followers_url": "https://api.github.com/users/ngreader/followers",
		"following_url": "https://api.github.com/users/ngreader/following{/other_user}",
		"gists_url": "https://api.github.com/users/ngreader/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/ngreader/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/ngreader/subscriptions",
		"organizations_url": "https://api.github.com/users/ngreader/orgs",
		"repos_url": "https://api.github.com/users/ngreader/repos",
		"events_url": "https://api.github.com/users/ngreader/events{/privacy}",
		"received_events_url": "https://api.github.com/users/ngreader/received_events",
		"type": "User",
		"site_admin": false
	},
	{
		"login": "justinstewart",
		"id": 667956,
		"node_id": "MDQ6VXNlcjY2Nzk1Ng==",
		"avatar_url": "https://avatars.githubusercontent.com/u/667956?v=4",
		"gravatar_id": "",
		"url": "https://api.github.com/users/justinstewart",
		"html_url": "https://github.com/justinstewart",
		"followers_url": "https://api.github.com/users/justinstewart/followers",
		"following_url": "https://api.github.com/users/justinstewart/following{/other_user}",
		"gists_url": "https://api.github.com/users/justinstewart/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/justinstewart/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/justinstewart/subscriptions",
		"organizations_url": "https://api.github.com/users/justinstewart/orgs",
		"repos_url": "https://api.github.com/users/justinstewart/repos",
		"events_url": "https://api.github.com/users/justinstewart/events{/privacy}",
		"received_events_url": "https://api.github.com/users/justinstewart/received_events",
		"type": "User",
		"site_admin": false
	}
]
"""
